[tool.coverage.run]
omit = [
  "*/migrations/**",
  "*/settings/**",
  "*/tests/**",
  "*apps.py",
  "*urls.py",
  "*wsgi.py",
  "manage.py",
]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "def __repr__", "if TYPE_CHECKING:"]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov=metis --cov-report=html"
markers = [
  "api: mark a test as an `api` test",
  "site: mark a test as an `site` test",
]
DJANGO_SETTINGS_MODULE = "metis.settings.test"

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.isort]
lines-after-imports = 2

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["B026", "SIM105"]
