[tool.black]
line-length = 120

[tool.coverage.run]
omit = ["*apps.py", "*migrations/*", "*settings/*", "*tests/*", "*migratedata.py", "*urls.py", "*wsgi.py", "manage.py"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "def __repr__"]
show_missing = true

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "epione.settings"

[tool.pytest.ini_options]
addopts = "--cov=epione --cov-report=html"
DJANGO_SETTINGS_MODULE = "epione.settings.test"
