# Generated by Django 4.2.1 on 2023-05-27 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0002_remove_tmp_audiologo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmpData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rijksregisternummer", models.CharField(max_length=160)),
                ("address", models.CharField(max_length=160)),
                ("city", models.CharField(max_length=160)),
                ("has_kot", models.BooleanField(default=False)),
                ("address2", models.CharField(blank=True, max_length=160, null=True)),
                ("city2", models.CharField(blank=True, max_length=160, null=True)),
                ("has_car", models.BooleanField(default=False)),
                ("is_interested_in_foreign", models.BooleanField(default=False)),
                ("can_speak_french", models.BooleanField(default=False)),
                ("can_speak_details", models.CharField(blank=True, max_length=160, null=True)),
                ("has_special_status", models.BooleanField(default=False)),
                ("is_werkstudent", models.BooleanField(default=False)),
                ("is_beursstudent", models.BooleanField(default=False)),
                ("mobile_phone", models.CharField(blank=True, max_length=160, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tmp_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metis_tmp_user_data",
            },
        ),
    ]
