# Generated by Django 4.2.1 on 2023-06-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0003_tmp_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="program_internship",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periods",
                to="metis.programinternship",
            ),
            preserve_default=False,
        ),
    ]
