# Generated by Django 4.2.1 on 2023-06-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0004_alter_period_program_internship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("preplanning", "Preplanning"),
                    ("concept", "Concept"),
                    ("definitive", "Definitive"),
                    ("cancelled", "Cancelled"),
                    ("unsuccessful", "Unsuccessful"),
                ],
                default="concept",
                max_length=20,
            ),
        ),
    ]
