# Generated by Django 4.2.1 on 2023-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0005_remove_internship_is_valid_internship_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
