# Generated by Django 4.2.1 on 2023-06-12 10:10

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0006_contact_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="office_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name="signature",
            table="metis_log_signature",
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("obj_class", models.CharField(blank=True, max_length=64, null=True)),
                ("add_office_in_bcc", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_templates",
                        to="metis.education",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metis_email_template",
                "ordering": ["education", "code"],
                "unique_together": {("education", "code")},
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("to", models.CharField(max_length=255)),
                ("bcc", models.CharField(blank=True, max_length=255, null=True)),
                ("reply_to", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="metis.emailtemplate"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metis_log_email",
            },
        ),
    ]
