# Generated by Django 4.2.1 on 2023-06-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0007_emails_redux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="metis.emailtemplate",
            ),
        ),
    ]
