# Generated by Django 4.2.2 on 2023-06-19 11:39

import django.db.models.deletion
import django.utils.timezone

from django.db import migrations, models


def update_data(apps, schema_editor):
    EmailLog = apps.get_model("metis", "EmailLog")

    for log in EmailLog.objects.all():
        if log.template:
            log.education = log.template.education
        log.reply_to = f'["{log.reply_to}"]'
        log.to = f'["{log.to}"]'
        log.bcc = f'["{log.bcc}"]' if log.bcc else "[]"
        log.created_at = log.sent_at
        log.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0011_project_place_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emaillog",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_logs",
                to="metis.education",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="from_email",
            field=models.CharField(default="Metis <metis@ugent.be>", max_length=255),
            preserve_default=False,
        ),
        # -----
        migrations.RunPython(update_data),
        # -----
        migrations.AlterField(
            model_name="emaillog",
            name="bcc",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="reply_to",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="to",
            field=models.JSONField(default=list),
        ),
    ]
