# Generated by Django 4.2.2 on 2023-06-20 07:15

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


def update_user_id(apps, schema_editor):
    EmailLog = apps.get_model("metis", "EmailLog")
    EmailAddress = apps.get_model("account", "EmailAddress")

    for log in EmailLog.objects.all():
        try:
            user = EmailAddress.objects.get(email=log.to[0]).user
            log.to_user = user
            log.save()
        except EmailAddress.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0012_improve_email_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="user",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="metis.education",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="metis.emailtemplate",
            ),
        ),
        # -----
        migrations.RunPython(update_user_id),
        # -----
    ]
