# Generated by Django 4.2.2 on 2023-06-21 13:44

import django.db.models.deletion

from django.db import migrations, models


def update_project_ids(apps, schema_editor):
    CustomForm = apps.get_model("metis", "CustomForm")

    for form in CustomForm.objects.all():
        project = form.education.projects.get(name="AJ23-24")
        if project:
            form.project_id = form.education.projects.get(name="AJ23-24").id
            form.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0014_custom_place_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="project",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="forms", to="metis.project"
            ),
            preserve_default=False,
        ),
        # -----
        migrations.RunPython(update_project_ids),
        # -----
        migrations.AlterUniqueTogether(
            name="customform",
            unique_together={("project", "code", "version")},
        ),
        migrations.RemoveField(
            model_name="customform",
            name="education",
        ),
        migrations.AlterField(
            model_name="customformresponse",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="responses", to="metis.customform"
            ),
        ),
    ]
