# Generated by Django 4.2.2 on 2023-06-22 12:18

from django.db import migrations, models
from time import sleep

from metis.services.mapbox import Mapbox


def update_mapbox_feature(apps, schema_editor):
    Address = apps.get_model("metis", "Address")

    with Mapbox() as mapbox:
        for address in Address.objects.all():
            try:
                geo = mapbox.geocode(f"{address.address}, {address.postcode} {address.city}, {address.country.name}")
                if geo:
                    address.mapbox_feature = geo.to_dict()
                    address.save()
                    sleep(0.25)
            except Exception as e:
                print(f"Error: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0015_link_forms_to_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mapbox_feature",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        # -----
        migrations.RunPython(update_mapbox_feature),
        # -----
    ]
