# Generated by Django 4.2.2 on 2023-06-23 11:34

from django.db import migrations


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0016_tweak_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regionpreference",
            name="preference",
        ),
        migrations.RemoveField(
            model_name="regionpreference",
            name="region",
        ),
        migrations.RemoveField(
            model_name="place",
            name="region",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="regions",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.DeleteModel(
            name="RegionPreference",
        ),
    ]
