# Generated by Django 4.2.4 on 2023-08-24 10:35

from django.db import migrations, models
import django.db.models.deletion


def migrate_questionings(apps, schema_editor):
    ImportantDate = apps.get_model("metis", "ImportantDate")

    # bulk save to skip auto_now_add
    updates = []

    for important_date in ImportantDate.objects.all():
        important_date.form_definition = important_date.form.definition if important_date.form else {}
        updates.append(important_date)

    ImportantDate.objects.bulk_update(updates, ["form_definition"])


def migrate_responses(apps, schema_editor):
    CustomFormResponse = apps.get_model("metis", "CustomFormResponse")

    # bulk save to skip auto_now_add
    updates = []

    for response in CustomFormResponse.objects.all():
        response.questioning_id = response.form_id
        updates.append(response)

    CustomFormResponse.objects.bulk_update(updates, ["questioning_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0017_fix_pending_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="importantdate",
            name="form_definition",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="importantdate",
            name="type",
            field=models.CharField(
                choices=[
                    ("project_place_availability", "ProjectPlace availability"),
                    ("project_place_information", "ProjectPlace information"),
                    ("student_information", "Student information"),
                    ("student_tops", "Student preferences"),
                ],
                max_length=32,
            ),
        ),
        # -----
        migrations.RunPython(migrate_questionings),
        # -----
        migrations.RemoveField(
            model_name="importantdate",
            name="form",
        ),
        migrations.AlterModelTable(
            name="importantdate",
            table="metis_project_questionings",
        ),
        migrations.RenameModel("ImportantDate", "Questioning"),
        migrations.AlterField(
            model_name="customformresponse",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="responses", to="metis.questioning"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customformresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="customformresponse",
            name="questioning",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="responses", to="metis.questioning"
            ),
            preserve_default=False,
        ),
        # -----
        migrations.RunPython(migrate_responses),
        # -----
        migrations.AlterUniqueTogether(
            name="customformresponse",
            unique_together={("content_type", "object_id", "questioning")},
        ),
        migrations.RemoveField(
            model_name="customformresponse",
            name="form",
        ),
        migrations.AlterModelTable(
            name="customformresponse",
            table="metis_rel_form_response",
        ),
        migrations.RenameModel("CustomFormResponse", "FormResponse"),
        migrations.DeleteModel(
            name="customform",
        ),
        migrations.AlterField(
            model_name="questioning",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionings",
                to="metis.period",
            ),
        ),
        migrations.AlterField(
            model_name="questioning",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questionings", to="metis.project"
            ),
        ),
    ]
