# Generated by Django 4.2.5 on 2023-09-25 10:53

import uuid

from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    Signature = apps.get_model("metis", "Signature")

    for signature in Signature.objects.all():
        signature.uuid = uuid.uuid4()
        signature.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0019_migrate_tmp_student_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # -----
        migrations.RunPython(generate_unique_uuids),
        # -----
        migrations.AlterField(
            model_name="signature",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
