# Generated by Django 4.2.5 on 2023-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0020_signature_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioning",
            name="email_add_office_in_bcc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questioning",
            name="email_body",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questioning",
            name="email_subject",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
