# Generated by Django 4.2.5 on 2023-09-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0021_questioning_email_add_office_in_bcc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectplace",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
