# Generated by Django 4.2.5 on 2023-10-02 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_initial_mentors(apps, schema_editor) -> None:
    """Add initial mentors to internships."""
    Internship = apps.get_model("metis", "Internship")
    Mentor = apps.get_model("metis", "Mentor")
    User = apps.get_model("metis", "User")

    try:
        bot = User.objects.get(username="metis")
    except User.DoesNotExist:
        bot = None

    for internship in Internship.objects.filter(project__name="AJ23-24"):
        if internship.mentors.exists():
            continue

        if internship.project_place.place.contacts.filter(is_mentor=True).count() > 1:
            # If there are more than one mentors, we don't know which we should add, so we don't add any.
            continue

        for available_mentor in internship.project_place.place.contacts.filter(is_mentor=True):
            mentor = Mentor(internship=internship, user=available_mentor.user)
            mentor.created_by = bot
            mentor.updated_by = bot
            mentor.save()


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0022_projectplace_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mentors", to="metis.internship"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mentorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metis_internship_mentors",
                "unique_together": {("internship", "user")},
            },
        ),
        # -----
        migrations.RunPython(add_initial_mentors),
        # -----
    ]
