# Generated by Django 4.2.5 on 2023-10-04 9:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0024_remove_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time_am", models.TimeField(blank=True, null=True)),
                ("end_time_am", models.TimeField(blank=True, null=True)),
                ("start_time_pm", models.TimeField(blank=True, null=True)),
                ("end_time_pm", models.TimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="timesheets", to="metis.internship"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metis_internship_timesheet",
                "unique_together": {("internship", "date")},
            },
        ),
    ]
