# Generated by Django 4.2.5 on 2023-10-09 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_to_content_object(apps, schema_editor) -> None:
    """Migrate signatures to use content_type and object_id."""
    Signature = apps.get_model("metis", "Signature")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.get_for_model(apps.get_model("metis", "TextEntry"))

    # bulk save to skip auto_now_add
    updates = []

    for signature in Signature.objects.all():
        signature.content_type = ct
        signature.object_id = signature.text_entry_id
        signature.user = signature.student.user
        updates.append(signature)

    Signature.objects.bulk_update(updates, ["content_type", "object_id", "user"])


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("metis", "0025_timesheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatures",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signature",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signature",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signatures",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        # -----
        migrations.RunPython(migrate_to_content_object),
        # -----
        migrations.RemoveField(
            model_name="signature",
            name="student",
        ),
        migrations.RemoveField(
            model_name="signature",
            name="text_entry",
        ),
    ]
