# Generated by Django 4.2.6 on 2023-10-12 08:28

from django.db import migrations, models
import django.utils.timezone


def update_internship_dates(apps, schema_editor):
    Internship = apps.get_model("metis", "Internship")

    # bulk save to skip auto_now_add
    updates = []

    for internship in Internship.objects.all():
        internship.start_date = internship.custom_start_date or internship.period.start_date
        internship.end_date = internship.custom_end_date or internship.period.end_date
        updates.append(internship)

    Internship.objects.bulk_update(updates, ["start_date", "end_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0026_signature_with_content_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # -----
        migrations.RunPython(update_internship_dates),
        # -----
        migrations.RemoveField(
            model_name="internship",
            name="custom_end_date",
        ),
        migrations.RemoveField(
            model_name="internship",
            name="custom_start_date",
        ),
    ]
