# Generated by Django 4.2.6 on 2023-10-13 14:34

from django.db import migrations

import metis.utils.cryptography


def encrypt_existing_signatures(apps, schema_editor):
    Signature = apps.get_model("metis", "Signature")

    # bulk save to skip auto_now_add
    updates = []

    for signature in Signature.objects.all():
        signature.signed_text = metis.utils.cryptography.encrypt(signature.signed_text)
        updates.append(signature)

    Signature.objects.bulk_update(updates, ["signed_text"])


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0028_student_number"),
    ]

    operations = [
        # -----
        migrations.RunPython(encrypt_existing_signatures),
        # -----
        migrations.AlterField(
            model_name="signature",
            name="signed_text",
            field=metis.utils.cryptography.EncryptedTextField(),
        ),
    ]
