# Generated by Django 4.2.6 on 2023-10-17 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0029_encrypt_signatures"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
