# Generated by Django 4.2.6 on 2023-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0031_evaluations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="absence",
            name="status",
        ),
        migrations.AddField(
            model_name="absence",
            name="is_approved",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
