# Generated by Django 4.2.7 on 2023-11-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0033_evaluation_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioning",
            name="email_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questioning",
            name="email_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
