# Generated by Django 4.2.7 on 2023-11-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0037_refactor_evaluations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="case",
            name="reviewer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="case",
            name="reviewer_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="color",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="education",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="description_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="office_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="obj_class",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="questioning",
            name="email_body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="questioning",
            name="email_subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="number",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
