# Generated by Django 4.2.7 on 2023-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0038_ruff_dj"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
