# Generated by Django 4.2.8 on 2023-12-14 08:04

from django.db import migrations, models


def update_existing_internships(apps, schema_editor):
    """Update existing internships to be approved."""
    Internship = apps.get_model("metis", "Internship")
    Internship.objects.filter(project__education__code__in=["audio", "logo"]).update(is_approved=True)


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0039_place_is_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        # -----
        migrations.RunPython(update_existing_internships),
        # -----
    ]
