# Generated by Django 4.2.9 on 2024-01-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metis", "0040_internship_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="project_place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internships",
                to="metis.projectplace",
            ),
        ),
    ]
