# Generated by Django 4.2.9 on 2024-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0042_internship_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="oasis_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
