# Generated by Django 4.2.10 on 2024-03-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0043_student_oasis_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
    ]
