# Generated by Django 4.2.11 on 2024-03-13 09:24

import django.db.models.deletion
from django.db import migrations, models


def update_projects(apps, schema_editor) -> None:
    """Update projects for existing email logs."""
    EmailLog = apps.get_model("metis", "EmailLog")
    Project = apps.get_model("metis", "Project")

    # bulk save
    updates = []

    for email in EmailLog.objects.all():
        if email.education_id:
            try:
                project = Project.objects.get(education_id=email.education_id, name="AJ23-24")
            except Project.DoesNotExist:
                project = Project.objects.filter(education_id=email.education_id).first()
            email.project = project
            updates.append(email)

    EmailLog.objects.bulk_update(updates, ["project"])


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0045_email_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="metis.project",
            ),
        ),
        # -----
        migrations.RunPython(update_projects),
        # -----
        migrations.RemoveField(
            model_name="emaillog",
            name="education",
        ),
    ]
