# Generated by Django 4.2.11 on 2024-03-18 09:05

from django.db import migrations


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0046_email_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="template",
        ),
    ]
