# Generated by Django 4.2.11 on 2024-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0047_remove_emaillog_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="default_language",
            field=models.CharField(default="nl", max_length=2),
        ),
    ]
