# Generated by Django 4.2.12 on 2024-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0049_internship_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="evaluationform",
            name="email_add_office_in_bcc",
        ),
        migrations.RemoveField(
            model_name="evaluationform",
            name="email_body",
        ),
        migrations.RemoveField(
            model_name="evaluationform",
            name="email_subject",
        ),
        migrations.AddField(
            model_name="evaluation",
            name="is_self_evaluation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluationform",
            name="has_self_evaluations",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together={("internship", "intermediate", "is_self_evaluation")},
        ),
    ]
