# Generated by Django 4.2.13 on 2024-06-06 13:51

from django.db import migrations


def migrate_existing_data(apps, schema_editor) -> None:
    """Update for definition when `option_grid` is used."""
    Questioning = apps.get_model("metis", "Questioning")

    bulk_update = []

    for questioning in Questioning.objects.all():
        if "fieldsets" not in questioning.form_definition:
            continue

        for fieldset in questioning.form_definition["fieldsets"]:
            for field in fieldset["fields"]:
                if field["type"] == "option_grid":
                    field["rows"] = field.get("options", [])
                    field["options"] = field.get("columns", [])
                    del field["columns"]

        bulk_update.append(questioning)

    Questioning.objects.bulk_update(bulk_update, ["form_definition"])


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0052_timesheets_data"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_data),
    ]
