# Generated by Django 4.2.13 on 2024-07-03 07:43

from django.db import migrations, models


def update_existing_data(apps, schema_editor) -> None:
    """Update for definition when `option_grid` is used."""
    Questioning = apps.get_model("metis", "Questioning")

    bulk_update = []

    for questioning in Questioning.objects.all():
        type_target_group_mapping = {
            "project_place_availability": "project_places",
            "project_place_information": "project_places",
            "student_information": "students",
            "student_tops": "students",
        }

        questioning.target_group = type_target_group_mapping[questioning.type]
        bulk_update.append(questioning)

    Questioning.objects.bulk_update(bulk_update, ["target_group"])


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0053_custom_form_option_grid"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioning",
            name="target_group",
            field=models.CharField(
                choices=[
                    ("project_places", "Project Places"),
                    ("students", "Students"),
                    ("project_places_with_internship", "Project Places with Internship"),
                    ("students_with_internship", "Students with Internship"),
                ],
                default="project_places",
                max_length=32,
            ),
        ),
        # -----
        migrations.RunPython(update_existing_data),
    ]
