# Generated by Django 5.1.1 on 2024-10-03 08:58

from django.db import migrations


def update_timesheet_configuration(apps, schema_editor) -> None:
    """Update tags for existing email logs."""
    Education = apps.get_model("metis", "Education")

    # bulk save to skip auto_now_add
    updates = []

    for education in Education.objects.all():
        if "timesheets_with_comments" in education.config:
            education.config.pop("timesheets_with_comments")
            education.config["timesheets_extra_form"] = {
                "fieldsets": [
                    {
                        "fields": [
                            {
                                "code": "comments",
                                "label": {
                                    "en": "Comments",
                                    "nl": "Opmerkingen",
                                },
                                "type": "textarea",
                                "required": False,
                            },
                        ],
                    },
                    {
                        "legend": {
                            "nl": "Reflectie over deze week (1 keer in te vullen op einde van de week)",
                            "en": "Reflection about this week (to be filled in once at the end of the week)",
                        },
                        "fields": [
                            {
                                "code": "weekly_reflection",
                                "label": {
                                    "en": "What went well this week? What did you find difficult or what are your growth points?",  # noqa: E501
                                    "nl": "Wat is goed verlopen deze week? Waar had je het moeilijk mee of wat zijn je groeipunten?",  # noqa: E501
                                },
                                "type": "textarea",
                                "required": False,
                            },
                            {
                                "code": "weekly_action_points",
                                "label": {
                                    "en": "What action points do you set? Refer to your learning objectives if necessary",  # noqa: E501
                                    "nl": "Welke actiepunten stel je op? Verwijs hierbij eventueel naar je leerdoelen",
                                },
                                "type": "textarea",
                                "required": False,
                            },
                        ],
                    },
                ],
            }
            education.clean()
            updates.append(education)

    Education.objects.bulk_update(updates, ["config"])


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0055_place_locations"),
    ]

    operations = [
        # -----
        migrations.RunPython(update_timesheet_configuration),
        # -----
    ]
