# Generated by Django 5.1.2 on 2024-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0056_timesheet_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioning",
            name="disable_automatic_emails",
            field=models.BooleanField(default=False),
        ),
    ]
