# Generated by Django 5.1.2 on 2024-10-18 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import metis.models.validators


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0058_place_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.JSONField(default=list, validators=[metis.models.validators.validate_list_of_strings]),
        ),
        migrations.AddField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="tags",
            field=models.JSONField(default=list, validators=[metis.models.validators.validate_list_of_strings]),
        ),
        migrations.AlterField(
            model_name="textentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
