# Generated by Django 5.1.2 on 2024-10-21 10:44

from django.db import migrations, models

import metis.models.validators


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("metis", "0059_file_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="remark",
            name="tags",
            field=models.JSONField(default=list, validators=[metis.models.validators.validate_list_of_strings]),
        ),
    ]
